### ISSUE TITLE
Can you add the option to disable the /lobby command

### ISSUE THREAD

**Issue by Vehzx** [skygamezmc/SlashHub#2]
I have another plugin that requires this command and slashhub is overriding it, since I have no way to turn it off in slashhub this makes my other plugin obselete.

**Comment by skygamezmc** [comment]
Hello Vehzx. I appreciate your feedback. I am currently working on custom alias support which will effectively dissolve this problem. If possible do you mind telling me the plugin that is causing the clash?

**Comment by skygamezmc** [comment]
I have an update for you. Customizable aliases have been added and /lobby can now be removed from the alias list. I am unable to make /hub removable though. Hope this helps!

**Comment by Vehzx** [comment]
Sorry for seeing this late, update did indeed fix it, the /lobby command was through skywarsreloaded but I found out you can also customize the command in that plugin so I changed it there instead, thanks for this fix though I will use this for other things for sure.
